#!/usr/bin/env bash

##
# This is script is for usefule things to install via brew
# #

brew install awk
brew install cmake
brew install autojump
brew install fontforge
brew install libssh2
brew install ctags
#brew install macvim
brew install -v --force macvim
brew install tmux
gem install tmuxinator
brew install tmux-MacOSX-pasteboard
brew install reattach-to-user-namespace
brew install links
brew install wget
brew install urlview
brew install mairix
brew install slang lbdb urlview lynx
brew install mutt –-sidebar-patch –-trash-patch -–with-slang
brew install tree
brew install lbdb


# Gems that need to be installed
# This should be put in its own file
gem install terminal-notifier
sudo gem install cheat
