#!/usr/bin/env bash

##
# This is script is for usefule things to install via brew
# #

brew install awk
brew install cmake
brew install autojump
brew install fontforge
brew install libssh2
brew install ctags
brew install macvim
