#!/usr/bin/env bash

##
# This is script is for usefule things to install via brew
# #

brew install awk
brew install cmake
brew install autojump
brew install fontforge
brew install libssh2
brew install ctags
#brew install macvim
brew install -v --force macvim
brew install tmux
gem install tmuxinator
brew install tmux-MacOSX-pasteboard
brew install reattach-to-user-namespace
